# Task 1:

1.
Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
try:
    n = int(input("input an integer"))
    m = 5/n
except Exception as e:
    print("error :", e)
    

input an integer0
error : division by zero


2.
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [2]:
subjects=["Americans","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"]
for i in subjects:
    for j in verbs:
        for k in objects:
            print(i +" "+ j +" "+ k+".")
        

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# Task 2:

1.
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [4]:
import numpy as np
def matrix(vector, n,n1):
    
    if n1=='dec':
        out= np.array([x**(n-1-i) for x in vector for i in range(n)]).reshape(n,-1)
    elif n1== 'inc':
        out = np.array([x**i for x in vector for i in range(n)]).reshape(n,-1)
    
    return out
vector=(1,2,3,4,5)
n=5
print("Increasing order: \n",matrix(vector,n,'inc'))
print("decreasing order: \n",matrix(vector,n,'dec'))

Increasing order: 
 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
decreasing order: 
 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
